general_configs:
  num_plates: 4
  motors_to_move: ['curved_mirror', 'bottom_dielectric_plate', 'top_dielectric_plate']
    #motors_to_move: ['curved_mirror']
  wide_scan_start_freq: 15000000000
  wide_scan_stop_freq: 18000000000
  digitization_time: 30
  fft_size: 42002
  sampling_rate: 125000000
  vna_power: -5
  if_center: 29500000
  lo_power: 16
  widescan_interval: 10

measurement_configs:
  empty_resonator:
    initial_mirror_holder_spacing: 15.6 # cm
    starting_fo: 17480000000 # expected TEM_00-18 mode at initial spacing.
    sweep_points: 512
    increment_distance: 0.0001 #in.
    distance_to_move: 2 # cm
    sec_wait_for_na_transmission_averaging: 1
    sec_wait_for_na_reflection_averaging: 2
    averages: 16
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 3000000
    averaging_time_for_fo_guess_measurement: 1
    average_enable: 1 #must be 1 or 0

  dielectric_resonator:
    initial_mirror_holder_spacing: 13.55 # cm total length 14.55 cm
    starting_fo: 16949000000 # expected TEM_00-18 mode at initial spacing.
    sweep_points: 512
    increment_distance: 0.0001 #in.
    distance_to_move: 2 # cm
    sec_wait_for_na_transmission_averaging: 1.5
    sec_wait_for_na_reflection_averaging: 1.5
    averages: 16
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 20000000
    averaging_time_for_fo_guess_measurement: 1
    average_enable: 1 #must be 1 or 0

