general_configs:
  num_plates: 4
  #motors_to_move: ['curved_mirror', 'bottom_dielectric_plate', 'top_dielectric_plate']
  motors_to_move: ['curved_mirror', 'bottom_dielectric_plate'] #top dielectric plate stalls
    #motors_to_move: ['curved_mirror']
  wide_scan_start_freq: 15000000000
  wide_scan_stop_freq: 18000000000
  digitization_time: 100 
  fft_size: 50000
  sampling_rate: 125000000
  vna_power: -5
  if_center: 29500000
  lo_power: 16
  widescan_interval: 20

measurement_configs:
  empty_resonator:
    initial_mirror_holder_spacing: 15.6 # cm
      #starting_fo: 17480000000 # expected TEM_00-18 mode at initial spacing.
    sweep_points: 512
    increment_distance: 0.001 #in. This corresponds to 200 turns for the curved mirror motor.
    distance_to_move: 2 # cm
    sec_wait_for_na_transmission_averaging: 1
    sec_wait_for_na_reflection_averaging: 2
    averages: 16
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 3000000
    averaging_time_for_fo_guess_measurement: 1
    average_enable: 1 #must be 1 or 0

  dielectric_resonator:
    #initial_mirror_holder_spacing: 13.55 # cm total length 14.55 cm
    initial_mirror_holder_spacing: 13.938 # cm total length 13.8 cm
    sweep_points: 512
    widescan_sweep_points: 2048
    increment_distance: 0.0003 #in.
    distance_to_move: 1 # cm
    sec_wait_for_na_transmission_averaging: 1
    sec_wait_for_na_reflection_averaging: 1
    averages: 16
    narrow_scan_span_guess: 400000000
    narrow_scan_span_focus: 20000000
    averaging_time_for_fo_guess_measurement: 0.5 
    average_enable: 1 #must be 1 or 0
    disable_motors_while_digitizing: True
    stability_check: False

  dielectric_resonator_sit_on_frequency:
    #initial_mirror_holder_spacing: 13.55 # cm total length 14.55 cm
    initial_mirror_holder_spacing: 14.387 # cm total length 13.8 cm
    #starting_fo: 16949000000 # expected TEM_00-18 mode at initial spacing.
    #starting_fo:  17905500000# expected TEM_00-18 mode at initial spacing.
    sweep_points: 512
    widescan_sweep_points: 2048
    increment_distance: 0.0000 #in.
    distance_to_move: 2 # cm
    sec_wait_for_na_transmission_averaging: 1
    sec_wait_for_na_reflection_averaging: 1
    averages: 16
    narrow_scan_span_guess: 400000000
    narrow_scan_span_focus: 20000000
    averaging_time_for_fo_guess_measurement: 0.25
    average_enable: 1 #must be 1 or 0
    disable_motors_while_digitizing: True
    stability_check: False

