general_configs:
  num_plates: 4
  motors_to_move: ['curved_mirror', 'bottom_dielectric_plate', 'top_dielectric_plate']
    #motors_to_move: ['curved_mirror']
  wide_scan_start_freq: 15000000000
  wide_scan_stop_freq: 18000000000
  if_center: 30000000
  digitization_time: 30
  vna_power : -5

measurement_configs:
  empty_modemap:
    initial_mirror_holder_spacing: 15 #length in cm
    sec_wait_for_na_averaging: 4 #time in seconds
    average_enable: 1 # 1 or 0
    sweep_points: 1000
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    ifile_predicted_resonances: empty_analytical_resonances.txt
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 10000000
    tem0018_offset: -21000000
    fitting: true
    digitize: false
    averaging_time_for_fo_guess_measurement: 2
    distance_to_move: 3
    number_of_measurement_points: 50

  dielectric_modemap:
    initial_mirror_holder_spacing: 12.55 #length in cm
    sec_wait_for_na_averaging: 5 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span: 50000000
    ifile_predicted_resonances: 'dielectric_aperture_on_curved_mirror_measured.csv'
    sweep_points: 1000
    distance_to_move: 3
    number_of_measurement_points: 50
    digitize: false
    averaging_time_for_fo_guess_measurement: 2
    fitting: true
    tem0018_offset: -21000000

  ln2_empty_modemap:
    initial_mirror_holder_spacing: 13 #length in cm
    sec_wait_for_na_averaging: 4 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 10000000
    ifile_predicted_resonances: 'ln2_analytical_resonances.txt'
    sweep_points: 1000
    tem0018_offset: 0
    fitting: true
    digitize: false
    averaging_time_for_fo_guess_measurement: 2
    distance_to_move: 2.5 
    number_of_measurement_points: 50


  ln2_dielectric_modemap:
    initial_mirror_holder_spacing: 10 #length in cm
    sec_wait_for_na_averaging: 4 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span_guess: 600000000
    narrow_scan_span_focus: 10000000
    ifile_predicted_resonances: null
    sweep_points: 1000
    tem0018_offset: -21000000
    fitting: true
    digitize: false
    averaging_time_for_fo_guess_measurement: 2
    distance_to_move: 3
    number_of_measurement_points: 50
