general_configs:
  plate_thickness: 1/8
  num_plates: 4
  motors_to_move: ['curved_mirror', 'bottom_dielectric_plate', 'top_dielectric_plate']
  wide_scan_start_freq: 15000000000
  wide_scan_stop_freq: 18000000000

measurement_configs:
  empty_modemap:
    initial_mirror_holder_spacing: 15 #length in cm
    sec_wait_for_na_averaging: 2 #time in seconds
    average_enable: 1 # 1 or 0
    sweep_points: 1000
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    ifile_predicted_resonances: empty_analytical_resonances.txt
    narrow_scan_span: 20000000

  dielectric_modemap:
    initial_mirror_holder_spacing: 11.95 #length in cm
    sec_wait_for_na_averaging: 2 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span: 400000000
    ifile_predicted_resonances: dielectric_predicted_resonances.txt
    sweep_points: 1000

  ln2_empty_modemap:
    initial_mirror_holder_spacing: 00 #length in cm
    sec_wait_for_na_averaging: 2 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span: 400000000
    ifile_predicted_resonances: null
    sweep_points: 1000

  ln2_dielectric_modemap:
    initial_mirror_holder_spacing: 10 #length in cm
    sec_wait_for_na_averaging: 2 #time in seconds
    average_enable: 1 # 1 or 0
    averages: 16 # value doesn't matter is averable_enable = 0
    narrow_scan: True
    narrow_scan_span: 400000000
    ifile_predicted_resonances: null
    sweep_points: 1000
